/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ChatImport } from './routes/chat'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedReviewsImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedChatManagementImport } from './routes/_authenticated/chat-management'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as AuthenticatedProductsIndexImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedProductsNewImport } from './routes/_authenticated/products/new'

// Create/Update Routes

const ChatRoute = ChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedReviewsRoute = AuthenticatedReviewsImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedChatManagementRoute =
  AuthenticatedChatManagementImport.update({
    id: '/chat-management',
    path: '/chat-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

const AuthenticatedProductsIndexRoute = AuthenticatedProductsIndexImport.update(
  {
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedProductsNewRoute = AuthenticatedProductsNewImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authRouteImport
    }
    '/_authenticated/chat-management': {
      id: '/_authenticated/chat-management'
      path: '/chat-management'
      fullPath: '/chat-management'
      preLoaderRoute: typeof AuthenticatedChatManagementImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatManagementRoute: typeof AuthenticatedChatManagementRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatManagementRoute: AuthenticatedChatManagementRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/login': typeof authLoginRoute
  '/chat-management': typeof AuthenticatedChatManagementRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/products': typeof AuthenticatedProductsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof authLoginRoute
  '/chat-management': typeof AuthenticatedChatManagementRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/products': typeof AuthenticatedProductsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/chat-management': typeof AuthenticatedChatManagementRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/chat'
    | '/login'
    | '/chat-management'
    | '/reviews'
    | '/products/new'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/chat-management'
    | '/reviews'
    | '/products/new'
    | '/products'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/chat'
    | '/(auth)/login'
    | '/_authenticated/chat-management'
    | '/_authenticated/reviews'
    | '/_authenticated/'
    | '/_authenticated/products/new'
    | '/_authenticated/products/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ChatRoute: typeof ChatRoute
}

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ChatRoute: ChatRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/_authenticated",
        "/chat"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/chat-management",
        "/_authenticated/reviews",
        "/_authenticated/",
        "/_authenticated/products/new",
        "/_authenticated/products/"
      ]
    },
    "/chat": {
      "filePath": "chat.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx",
      "parent": "/(auth)"
    },
    "/_authenticated/chat-management": {
      "filePath": "_authenticated/chat-management.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/reviews": {
      "filePath": "_authenticated/reviews.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/products/new": {
      "filePath": "_authenticated/products/new.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/products/": {
      "filePath": "_authenticated/products/index.ts",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
